blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/thoukydides/homebridge-homeconnect/discussions
    about: If you are seeking support or have a question then please start a discussion instead of raising an issue.
  - name: ðŸš¦ Home Connect Server Status (unofficial)
    url: https://homeconnect.thouky.co.uk
    about: Check the unofficial Home Connect server status before reporting issues relating to problems communicating with the servers or controlling appliances.
  - name: â›” Authorisation error messages
    url: https://api-docs.home-connect.com/authorization?#authorization-errors
    about: Refer to the Home Connect Developer documentation for descriptions of errors that may occur during authorisation.
  - name: â›” Other error messages
    url: https://api-docs.home-connect.com/general?#api-errors
    about: Refer to the Home Connect Developer documentation for descriptions of errors that may occur during normal operation.
  - name: ðŸ“§ Contact the Home Connect Developer team
    url: https://developer.home-connect.com/support/contact
    about: Contact the Home Connect Developer team if you are having problems with authorisation, or if you want support for additional appliance programs or options.
